#Some general naming
system:
  name: ASVR_GO_1_DEBBUILD


#MongoDB Configuration
database:
  connection: mongodb://127.0.0.1:27017
  name: testasvrlocal


#MQTT Configuration
messaging:
  broker: 127.0.0.1
  port: 1883
  clientid: asvrgo1debbuild


#REST Interface Configuration
rest:
  port: 8520
  crt: /etc/opt/jane/REPLACE_ME.crt
  key: /etc/opt/jane/REPLACE_ME.key
  usehttp: true


#Web Interface Configuration
web:
  port: 8540
  crt: /etc/opt/jane/REPLACE_ME.crt
  key: /etc/opt/jane/REPLACE_ME.key
  usehttp: true  


#Web Interface Configuration
x3270:
  port: 3270
    

#Log file
logging:
  logfilelocation: /var/log/jane/ASVR_GO_1_DEBBUILD.log
  sessionupdatelogging: false
