#!/bin/sh

RED='\033[0;31m'
PURPLE='\033[0;35m'
NC='\033[0m'

echo "${PURPLE}Running post installation scripts${NC}"

echo "${PURPLE}Enabling Jane with systemd${NC}"
systemctl enable jane.service

#echo "${PURPLE}Starting Jane with systemd${NC}"
#systemctl start jane.service

echo "${RED}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!${NC}"
echo "${RED}   *** CHECK!!!!! **** ${NC}"
echo "${RED}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!${NC}"
echo "${RED} Edit the /opt/etc/jane/config.yaml ${NC}"
echo "${RED} Regenerate keys in /opt/etc/jane${NC}"
echo "${RED}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!${NC}"


echo "${PURPLE}Post installation scripts complete${NC}"


